myhtest<-function(samp1,h0mean,htype,alpha=0.05,psigma=0){
no=0
if(psigma<0|alpha<=0|alpha>=1){ 
	a=NULL 
	return(a) 
}
if(htype=="lefttail"){
	if(psigma>0){
		mean1<-mean(samp1)
		z=(mean1-h0mean)/(psigma/(length(samp1)^(1/2)))
		pvalue<-pnorm(z)
		zor<-qnorm(1-alpha)
		reject=(z<=-zor)
		ans<-c(pvalue,z,reject)
		return(ans)
	}
	if(psigma==0){
		mean1<-mean(samp1)
		std=sd(samp1)
		z=(mean1-h0mean)/(std/(length(samp1)^(1/2)))
		pvalue<-pnorm(z)
		zor<-qnorm(1-alpha)
		reject=(z<=-zor)
		ans<-c(pvalue,z,reject)

		return(ans)
	}
}
if(htype=="righttail"){
	if(psigma>0){
		mean1<-mean(samp1)
		z=(mean1-h0mean)/(psigma/(length(samp1)^(1/2)))
		pvalue<-1-pnorm(z)
		zor<-qnorm(1-alpha)
		reject=(z>=zor)
		ans<-c(pvalue,z,reject)
		return(ans)
	}
	if(psigma==0){
		mean1<-mean(samp1)
		std=sd(samp1)
		z=(mean1-h0mean)/(std/(length(samp1)^(1/2)))
		pvalue<-1-pnorm(z)
		zor<-qnorm(1-alpha)
		reject<-(z>=zor)
		ans<-c(pvalue,z,reject)
		return(ans)
	}
}
	if(htype=="twotail"){
		if(psigma>0){
			mean1<-mean(samp1)
			z=(mean1-h0mean)/(psigma/(length(samp1)^(1/2)))
			pvalue<-pnorm(z)*2
			pvalue1<-(1-pnorm(z))*2
			if(pvalue>pvalue1) 
				pvalue=pvalue1
			zor<-qnorm(1-(alpha/2))
			reject=(z>=zor)
			reject1=(z<=-zor)
			ans<-c(pvalue,z,reject|reject1)
			return(ans)
	}
	if(psigma==0){
		mean1<-mean(samp1)
		std=sd(samp1)
		z=(mean1-h0mean)/(std/(length(samp1)^(1/2)))
		pvalue<-pnorm(z)*2
		pvalue1<-(1-pnorm(z))*2
		if(pvalue>pvalue1)
		pvalue=pvalue1
		zor<-qnorm(1-(alpha/2))
		reject<-(z<=-zor)
		reject1<-(z>=zor)
		ans<-c(pvalue,z,reject|reject1)
		return(ans)
	}
	}
	if(no==0){
	a=NULL;
	return(a)
	}
}
mytype2<-function(h1mean,h0mean,type,alpha=0.05,psigma,size){
zcv=qnorm(1-alpha)
xcv=h0mean+zcv*(psigma/sqrt(size))
ztype2=(xcv-h1mean)/(psigma/sqrt(size))
if(type=="righttail"){
	ptype2=pnorm(ztype2)
}
if(type=="lefttail"){
	xcv=h0mean-zcv*(psigma/sqrt(size))
	ztype2=(xcv-h1mean)/(psigma/sqrt(size))
	ptype2=1-pnorm(ztype2)
}
ptest=1-ptype2
return (ptype2)

}
setwd("C:\\Users\\賴柏霖\\Desktop\\統計\\SME10e_EXCEL_DATA_SETS\\ch11 xlsx")
filename="Xr11-39.xlsx"
df1=loadWorkbook(filename)
df2=readWorksheet(df1,1)
sampl=df2$%Change
ans=myhtest(samp1,0,";lefttail",0.1,6)    //11.39 end
h1mean=mean(samp1)
type2error1=mytype2(h1mean,0,"righttail",0.1,6,50)
type2error2=mytype2(h1mean,0,"righttail",0.1,6,500)//在不改變alpha的情況下,增大size可以減低type2error的機率


